version: 2
jobs:
  build_all:
    working_directory: ~/airbrake-python
    docker:
      - image: randomknowledge/docker-pyenv-tox

    steps:
      - checkout

      - run:
          name: install
          command: |
            pip install -U pip virtualenv
            virtualenv airbrake
            source airbrake/bin/activate
            pip install tox tox-pyenv
            pyenv local 2.7.15 3.4.6 3.5.5
            tox -v --recreate

workflows:
  version: 2
  commit:
    jobs:
      - build_all
