version: 2
jobs:
  build:
    working_directory: ~/airbrake-python
    docker:
      - image: randomknowledge/docker-pyenv-tox:maintenance_update-versions

    steps:
      - checkout

      - run:
          name: install
          command: |
            pip install -U pip virtualenv
            virtualenv airbrake
            source airbrake/bin/activate
            pip install tox tox-pyenv
            pyenv local 2.7.18 3.5.10
            tox -v --recreate
